export const userUpdateFormInputs = [
	{
		name: 'name',
		label: 'Name',
		type: 'text',
		placeholder: 'Name',
		description: '',
		required: true,
	},
	{
		name: 'email',
		label: 'Email',
		type: 'email',
		placeholder: 'Email',
		description: '',
		required: true,
		disabled: true,
	},
	{
		name: 'currentPassword',
		label: 'Current Password',
		type: 'password',
		placeholder: 'Current Password',
		description: '',
		required: true,
	},
	{
		name: 'password',
		label: 'Password',
		type: 'password',
		placeholder: 'Password',
		description: '',
		required: true,
	},
	{
		name: 'confirmPassword',
		label: 'Confirm Password',
		type: 'password',
		placeholder: 'Confirm Password',
		description: '',
		required: true,
	},
];
